export const PROGRESS_SPINNER = 'PROGRESS_SPINNER';
export const PROGRESS_SPINNER_SHOW = 'PROGRESS_SPINNER_SHOW';
export const PROGRESS_SPINNER_HIDE = 'PROGRESS_SPINNER_HIDE';
export const LOG_IN = 'LOG_IN';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';
export const LOG_IN_PENDING = 'LOG_IN_PENDING';

export const IS_AUTHENTICATED = 'IS_AUTHENTICATED';
export const IS_AUTHENTICATED_SUCCESS = 'IS_AUTHENTICATED_SUCCESS';
export const IS_AUTHENTICATED_FAILURE = 'IS_AUTHENTICATED_FAILURE';
export const IS_AUTHENTICATED_PENDING = 'IS_AUTHENTICATED_PENDING';
export const IS_AUTHENTICATED_CLEARDETAILS = 'IS_AUTHENTICATED_CLEARDETAILS';


export const PROCESS_DATA = 'PROCESS_DATA';
export const PROCESS_DATA_LOADER_START = 'PROCESS_DATA_LOADER_START';
export const PROCESS_DATA_LOADER_END = 'PROCESS_DATA_LOADER_END';
export const PROCESS_DATA_SUCCESS_SPONSORED = 'PROCESS_DATA_SUCCESS_SPONSORED';
export const PROCESS_DATA_SUCCESS_NON_BLUEROOM = 'PROCESS_DATA_SUCCESS_NON_BLUEROOM';
export const PROCESS_DATA_SUCCESS_ADM_UNSPONSORED = 'PROCESS_DATA_SUCCESS_ADM_UNSPONSORED';

export const PROCESS_DATA_FAILURE = 'PROCESS_DATA_FAILURE';

export const DIRECTORY_DETAILS = 'DIRECTORY_DETAILS';
export const BLUEROOM_DETAILS = 'BLUEROOM_DETAILS';

export const DIRECTORY_DETAILS_FETCH = 'DIRECTORY_DETAILS_FETCH';
export const DIRECTORY_DETAILS_DATA_LOADER_START = 'DIRECTORY_DETAILS_DATA_LOADER_START';
export const DIRECTORY_DETAILS_DATA_LOADER_END = 'DIRECTORY_DETAILS_DATA_LOADER_END';

export const BLUEROOM_DETAILS_FETCH = 'BLUEROOM_DETAILS_FETCH';
export const BLUEROOM_DETAILS_DATA_LOADER_START = 'BLUEROOM_DETAILS_DATA_LOADER_START';
export const BLUEROOM_DETAILS_DATA_LOADER_END = 'BLUEROOM_DETAILS_DATA_LOADER_END';